/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.net.URL;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author ADMIN
 */
public class PcInfo extends javax.swing.JFrame {

    /**
     * Creates new form testUI
     */
    public PcInfo() {
        initComponents();
        tab1.setBackground(new Color(253,188,207));
        HWjTextField.setEditable(false);
        ProjTextField.setEditable(false);
        DisjTextField3.setEditable(false);
        OSjTextField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelMenuLeft = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        tabName1 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        tabName3 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        tabName4 = new javax.swing.JLabel();
        tab5 = new javax.swing.JPanel();
        tabName5 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        tabName2 = new javax.swing.JLabel();
        jPanelRight = new javax.swing.JPanel();
        jPanelRight1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProjTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        OSjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DisjTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        HWjTextField = new javax.swing.JTextField();
        jPanelRight4 = new javax.swing.JPanel();
        jPanelRight2 = new javax.swing.JPanel();
        jPanelRight3 = new javax.swing.JPanel();
        jPanelRight5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMain.setMaximumSize(new java.awt.Dimension(1000, 625));

        jPanelHeader.setBackground(new java.awt.Color(188, 133, 163));

        //jLabel5.setIcon(new javax.swing.ImageIcon((getClass().getResource("image/G (2).png")))); // NOI18N

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
                jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelHeaderLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 720, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
                jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
        );

        jPanelMenuLeft.setBackground(new java.awt.Color(249, 225, 224));

        tab1.setBackground(new java.awt.Color(254, 173, 185));
        tab1.setPreferredSize(new java.awt.Dimension(250, 43));
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        tabName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabName1.setText("OS & Hardware Information");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
                tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tabName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        tab1Layout.setVerticalGroup(
                tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tabName1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                .addContainerGap())
        );

        tab3.setBackground(new java.awt.Color(254, 173, 185));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        tabName3.setText("Home me");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
                tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tabName3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
        );
        tab3Layout.setVerticalGroup(
                tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tabName3, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                                .addContainerGap())
        );

        tab4.setBackground(new java.awt.Color(254, 173, 185));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        tabName4.setText("Home me");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
                tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab4Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(tabName4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab4Layout.setVerticalGroup(
                tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tabName4, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                                .addContainerGap())
        );

        tab5.setBackground(new java.awt.Color(254, 173, 185));
        tab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab5MouseClicked(evt);
            }
        });

        tabName5.setText("Home me");

        javax.swing.GroupLayout tab5Layout = new javax.swing.GroupLayout(tab5);
        tab5.setLayout(tab5Layout);
        tab5Layout.setHorizontalGroup(
                tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab5Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tabName5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
        );
        tab5Layout.setVerticalGroup(
                tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tabName5, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                                .addContainerGap())
        );

        tab2.setBackground(new java.awt.Color(254, 173, 185));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        tabName2.setText("Hệ điêu");

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
                tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tabName2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
        );
        tab2Layout.setVerticalGroup(
                tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tab2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tabName2, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelMenuLeftLayout = new javax.swing.GroupLayout(jPanelMenuLeft);
        jPanelMenuLeft.setLayout(jPanelMenuLeftLayout);
        jPanelMenuLeftLayout.setHorizontalGroup(
                jPanelMenuLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tab3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tab5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tab2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tab1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanelMenuLeftLayout.setVerticalGroup(
                jPanelMenuLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMenuLeftLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tab5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(170, Short.MAX_VALUE))
        );

        jPanelRight.setBackground(new java.awt.Color(255, 204, 204));
        jPanelRight.setLayout(new javax.swing.OverlayLayout(jPanelRight));

        jPanelRight1.setBackground(new java.awt.Color(240, 197, 213));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Operation System");

        ProjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProjTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Processor");

        OSjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OSjTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Display");

        DisjTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisjTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Hardware Information");

        HWjTextField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        HWjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HWjTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRight1Layout = new javax.swing.GroupLayout(jPanelRight1);
        jPanelRight1.setLayout(jPanelRight1Layout);
        jPanelRight1Layout.setHorizontalGroup(
                jPanelRight1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelRight1Layout.createSequentialGroup()
                                .addGroup(jPanelRight1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelRight1Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addGroup(jPanelRight1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(ProjTextField)
                                                        .addComponent(DisjTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)))
                                        .addGroup(jPanelRight1Layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelRight1Layout.createSequentialGroup()
                                                .addGap(122, 122, 122)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelRight1Layout.createSequentialGroup()
                                                .addGap(121, 121, 121)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addGroup(jPanelRight1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRight1Layout.createSequentialGroup()
                                                .addComponent(HWjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRight1Layout.createSequentialGroup()
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(122, 122, 122))))
                        .addGroup(jPanelRight1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelRight1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(OSjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(437, Short.MAX_VALUE)))
        );
        jPanelRight1Layout.setVerticalGroup(
                jPanelRight1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelRight1Layout.createSequentialGroup()
                                .addGroup(jPanelRight1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelRight1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(HWjTextField))
                                        .addGroup(jPanelRight1Layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(115, 115, 115)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ProjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(DisjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(61, Short.MAX_VALUE))
                        .addGroup(jPanelRight1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelRight1Layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(OSjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(327, Short.MAX_VALUE)))
        );

        jPanelRight.add(jPanelRight1);

        jPanelRight4.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanelRight4Layout = new javax.swing.GroupLayout(jPanelRight4);
        jPanelRight4.setLayout(jPanelRight4Layout);
        jPanelRight4Layout.setHorizontalGroup(
                jPanelRight4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanelRight4Layout.setVerticalGroup(
                jPanelRight4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 490, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanelRight4);

        jPanelRight2.setBackground(new java.awt.Color(102, 255, 0));

        javax.swing.GroupLayout jPanelRight2Layout = new javax.swing.GroupLayout(jPanelRight2);
        jPanelRight2.setLayout(jPanelRight2Layout);
        jPanelRight2Layout.setHorizontalGroup(
                jPanelRight2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanelRight2Layout.setVerticalGroup(
                jPanelRight2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 490, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanelRight2);

        jPanelRight3.setBackground(new java.awt.Color(255, 51, 102));

        javax.swing.GroupLayout jPanelRight3Layout = new javax.swing.GroupLayout(jPanelRight3);
        jPanelRight3.setLayout(jPanelRight3Layout);
        jPanelRight3Layout.setHorizontalGroup(
                jPanelRight3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanelRight3Layout.setVerticalGroup(
                jPanelRight3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 490, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanelRight3);

        jPanelRight5.setBackground(new java.awt.Color(240, 197, 213));

        javax.swing.GroupLayout jPanelRight5Layout = new javax.swing.GroupLayout(jPanelRight5);
        jPanelRight5.setLayout(jPanelRight5Layout);
        jPanelRight5Layout.setHorizontalGroup(
                jPanelRight5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanelRight5Layout.setVerticalGroup(
                jPanelRight5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 490, Short.MAX_VALUE)
        );

        jPanelRight.add(jPanelRight5);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
                jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addComponent(jPanelMenuLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelMainLayout.setVerticalGroup(
                jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelMenuLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        jPanelRight1.setVisible(true);
        jPanelRight2.setVisible(false);
        jPanelRight3.setVisible(false);
        jPanelRight4.setVisible(false);
        jPanelRight5.setVisible(false);
        tab1.setBackground(new Color(254,173,185));
        tab2.setBackground(new Color(254,173,185));
        tab3.setBackground(new Color(254,173,185));
        tab4.setBackground(new Color(254,173,185));
        tab5.setBackground(new Color(254,173,185));



    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        jPanelRight5.setVisible(false);
        jPanelRight2.setVisible(true);
        jPanelRight3.setVisible(false);
        jPanelRight4.setVisible(false);
        jPanelRight1.setVisible(false);
        tab2.setBackground(new Color(253,188,207));
        tab1.setBackground(new Color(254,173,185));
        tab3.setBackground(new Color(254,173,185));
        tab4.setBackground(new Color(254,173,185));
        tab5.setBackground(new Color(254,173,185));
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        jPanelRight5.setVisible(false);
        jPanelRight2.setVisible(false);
        jPanelRight3.setVisible(true);
        jPanelRight4.setVisible(false);
        jPanelRight1.setVisible(false);
        tab3.setBackground(new Color(253,188,207));
        tab1.setBackground(new Color(254,173,185));
        tab2.setBackground(new Color(254,173,185));
        tab4.setBackground(new Color(254,173,185));
        tab5.setBackground(new Color(254,173,185));
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        jPanelRight5.setVisible(false);
        jPanelRight2.setVisible(false);
        jPanelRight3.setVisible(false);
        jPanelRight4.setVisible(true);
        jPanelRight1.setVisible(false);
        tab4.setBackground(new Color(253,188,207));
        tab2.setBackground(new Color(254,173,185));
        tab3.setBackground(new Color(254,173,185));
        tab1.setBackground(new Color(254,173,185));
        tab5.setBackground(new Color(254,173,185));
    }//GEN-LAST:event_tab4MouseClicked

    private void tab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab5MouseClicked
        jPanelRight5.setVisible(true);
        jPanelRight2.setVisible(false);
        jPanelRight3.setVisible(false);
        jPanelRight4.setVisible(false);
        jPanelRight1.setVisible(false);
        tab5.setBackground(new Color(253,188,207));
        tab2.setBackground(new Color(254,173,185));
        tab3.setBackground(new Color(254,173,185));
        tab4.setBackground(new Color(254,173,185));
        tab1.setBackground(new Color(254,173,185));
    }//GEN-LAST:event_tab5MouseClicked

    private void ProjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProjTextFieldActionPerformed

    }//GEN-LAST:event_ProjTextFieldActionPerformed

    private void OSjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OSjTextFieldActionPerformed

    }//GEN-LAST:event_OSjTextFieldActionPerformed

    private void DisjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisjTextField3ActionPerformed

    }//GEN-LAST:event_DisjTextField3ActionPerformed

    private void HWjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HWjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HWjTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PcInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PcInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PcInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PcInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PcInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DisjTextField3;
    private javax.swing.JTextField HWjTextField;
    private javax.swing.JTextField OSjTextField;
    private javax.swing.JTextField ProjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMenuLeft;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelRight1;
    private javax.swing.JPanel jPanelRight2;
    private javax.swing.JPanel jPanelRight3;
    private javax.swing.JPanel jPanelRight4;
    private javax.swing.JPanel jPanelRight5;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    private javax.swing.JLabel tabName1;
    private javax.swing.JLabel tabName2;
    private javax.swing.JLabel tabName3;
    private javax.swing.JLabel tabName4;
    private javax.swing.JLabel tabName5;
    // End of variables declaration//GEN-END:variables
}
