/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import oshi.SystemInfo;
import oshi.hardware.HardwareAbstractionLayer;
import oshi.hardware.UsbDevice;

import javax.swing.*;

/**
 *
 * @author ADMIN
 */
public class USBDeviceJpanel extends javax.swing.JPanel {

    public static final int REFRESH_SLOW = 5000;
    public USBDeviceJpanel(SystemInfo si) {
        initComponents(si.getHardware());
        setEdiable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(HardwareAbstractionLayer hal) {

        jPnUSB = new javax.swing.JPanel();
        jLblUSB = new javax.swing.JLabel();
        jScrllPnUsb = new javax.swing.JScrollPane();
        jtaUSB = new javax.swing.JTextArea();

        setRequestFocusEnabled(false);

        jPnUSB.setBackground(new java.awt.Color(161, 201, 241));
        jPnUSB.setPreferredSize(new java.awt.Dimension(800, 414));

        jLblUSB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblUSB.setText("USB Devices");

        jtaUSB.setColumns(20);
        jtaUSB.setRows(5);
        jScrllPnUsb.setViewportView(jtaUSB);

        javax.swing.GroupLayout jPnUSBLayout = new javax.swing.GroupLayout(jPnUSB);
        jPnUSB.setLayout(jPnUSBLayout);
        jPnUSBLayout.setHorizontalGroup(
            jPnUSBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnUSBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblUSB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrllPnUsb, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPnUSBLayout.setVerticalGroup(
            jPnUSBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnUSBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblUSB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrllPnUsb, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnUSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnUSB, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        Timer timer = new Timer(REFRESH_SLOW, e -> jtaUSB.setText(getUsbString(hal)));
        timer.start();
    }// </editor-fold>//GEN-END:initComponents

    private static String getUsbString(HardwareAbstractionLayer hal) {
        StringBuilder sb = new StringBuilder();
        boolean first = true;
        for (UsbDevice usbDevice : hal.getUsbDevices(true)) {
            if (first) {
                first = false;
            } else {
                sb.append('\n');
            }
            sb.append(String.valueOf(usbDevice));
        }
        return sb.toString();
    }

    public void setEdiable(boolean flag){
     jtaUSB.setEditable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblUSB;
    private javax.swing.JPanel jPnUSB;
    private javax.swing.JScrollPane jScrllPnUsb;
    private javax.swing.JTextArea jtaUSB;
    // End of variables declaration//GEN-END:variables
}
